language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

before_script:

syntax-check:
    - "find . -name '*.php' -print0 | xargs -0 -n1 php -l"

unit-test:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr